# Generated by Django 2.1.2 on 2018-12-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockname', models.CharField(blank=True, max_length=50, null=True)),
                ('stockcode', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
    ]
