# Generated by Django 2.1.2 on 2018-11-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=20)),
                ('intro_text', models.CharField(max_length=1000)),
                ('company_text', models.CharField(max_length=200)),
                ('hot_index', models.IntegerField()),
            ],
        ),
    ]
