# Generated by Django 2.1.3 on 2018-12-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20181223_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=80, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('keystock', models.TextField(blank=True, null=True)),
                ('senti', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temp_news',
                'managed': False,
            },
        ),
    ]
