# Generated by Django 2.1.3 on 2018-12-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_choice', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stocks',
            field=models.ManyToManyField(to='stock_choice.Stock'),
        ),
    ]
